name: candito5_week
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #Core
  flutter_riverpod: ^2.4.6
  kartal: ^3.5.0
  flutter_svg: ^2.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^5.1.0


flutter:

  uses-material-design: true

  assets:
    - assets/image/
    - assets/icons/
